import {StyleSheet} from 'react-native'


export default StyleSheet.create({
  container:{
    flex:1,
    justifyContent:'center',
    alignItems:'center',
  },
  // Segunda seção após Header,
  // Contendo as informações de saldo e banco
  content:{
    width:'100%',
    justifyContent:'center',
    alignItems:'center',
    marginTop:30,             
  },
  titulo:{
    width:'100%',
    paddingHorizontal:25,
    marginBottom:10,
  },
  textTitulo:{
    fontSize:15,
    fontFamily:'gotham-medium',
    color:'#691CC7',
  },
  contentAccount:{
    flexDirection:'row',
    justifyContent:'space-between',
    alignItems:'center',
    width:'90%',
    height:100,
    borderWidth:2,
    borderColor:'#F4CDBB',
    borderRadius:20,
    padding:15,
  },
  boxAccount:{
    width:180,
  },
  boxBank:{
    flexDirection:'row',
    justifyContent:'flex-start',
    alignItems:'center',
  },
  iconArrow:{
    width:10,
    height:10,
    marginLeft:20,
  },
  textAcc:{
    fontSize:9,
    fontFamily:'gotham-medium',
    color:'#7C7C7C',
  },
  textBank:{
    fontFamily:'gotham-medium',
    fontSize:13,
    color:'#7C7C7C',
    marginBottom:5,
  },
  Mountante:{
    padding:5,
  },
  textSaldo:{
    fontSize:9,
    fontFamily:'gotham-medium',
    color:'#7C7C7C',
  },
  textMoney:{
    fontSize:13,
    fontFamily:'gotham-medium',
    color:'#7C7C7C',
  },
  textTrans:{
    width:'100%',
    padding:3,
    backgroundColor:'#F9A179',
    borderRadius:5,
    color:'#fff',
    fontSize:13,
    textAlign:'center',
    elevation:2,
    },
    // Botões flutuantes
    sectionButtons:{
      flexDirection:'row',
      width:'100%',
      justifyContent:'space-around',
      marginTop:16,
    },
    button:{
      width:170,
      backgroundColor:'#691CC7',
      flexDirection:'row',
      alignItems:'center',
      justifyContent:'space-evenly',
      borderRadius:10,
    },
    iconCirclePlus:{
      width:20,
      height:20,
    },
    buttonText:{
      color:'#fff',
      fontSize:10,
      fontFamily:'gotham-bold',
      textAlign:'left',
      paddingVertical:10
    },
    // Botões Flutuantes de Configuração
    sectionConfig:{
      flexDirection:'row',
      width:'100%',
      justifyContent:'flex-end',
      paddingHorizontal:18,
      marginTop:25,
    },
    buttonIcon:{},
    iconImg:{
      width:25,
      height:25,
    },
    boxButons:{
      width:95,
      flexDirection:'row',
      justifyContent:'space-around',
    },
    background:{
      backgroundColor:'#fff',
    },
    // Card de transações
    cardFinancer:{
      backgroundColor:'#fff',
      width:'90%',
      borderRadius:10,
      marginTop:15,
      marginBottom:20,
      padding:8,
    },
    headerCard:{
      flexDirection:'row',
      width:'100%',
      justifyContent:'space-between',
      alignItems:'center',
      borderBottomWidth:1,
      borderColor:'#ADADAD',
      padding:5,
    },
    tituloCard:{
      color:'#691CC7',
      fontSize:9,
      fontFamily:'gotham-medium',
    },
    arrowIcon:{
      width:15,
      height:15,
    },
    contentCard:{
      padding:13,
    },
    textCard:{
      color:'#8B8B8B',
      fontSize:9,
      fontFamily:'gotham-regular',
      lineHeight:16,
    },
    textAlertCard:{
      width:'50%',
      backgroundColor:'#C3C3C3',
      color:'#fff',
      borderRadius:50,
      marginTop:9,
      padding:3,
      fontSize:10,
      fontFamily:'gotham-medium',
      textAlign:'center',
    },
    footerCard:{
      flexDirection:'row',
      justifyContent:'space-between',
      alignItems:'center',
      borderTopWidth:1,
      paddingHorizontal:5,
      paddingVertical:15,
    },
    textCash:{
       fontSize:10,
       fontFamily:'gotham-medium',
       color:'#6D8E38',
    },
    boxIcons:{
      flexDirection:'row',
      width:100,
      justifyContent:'space-around',
    },
    // Seção de Saldo
    containerSaldo:{
      flexDirection:'row',
      justifyContent:'space-between',
      alignItems:'center',
      paddingHorizontal:21,
      paddingVertical:16,
      borderWidth:1,
      borderColor:'#F4CDBB',
      width:'90%',
      borderRadius:50,
      marginBottom:20,
    },
    textSaldoFinal:{
      color:'#7C7C7C',
      fontSize:9,
      fontFamily:'gotham-medium',
    },
    textCashFinal:{
      color:'#7C7C7C',
      fontSize:13,
      fontFamily:'gotham-medium',
    },
    
})